### PR TITLE
1.1.0-Update

### PR DESCRIPTION
**Pull request by Awesomegamergame**
start a pull request for github action debug builds

### CODE REVIEW

**Comment by Awesomegamergame** [comment]
waiting for github actions

**Comment by Awesomegamergame** [comment]
github actions finished review it and run the program see if there is anymore features that could be added to make the slideshow mode better.

PS. the debug build to test is in github actions or you can just build the code yourself

**Comment by ArsiaC01** [comment]
Awesome, I'll take a look at it later today

**Comment by Awesomegamergame** [comment]
bruh you merged it without me i was about to add another commit to this branch but oh well whats done is done. @ArsiaC01

**Comment by ArsiaC01** [comment]
Sorry @awesomegamergame, I left the branch open though 😬

**Comment by Awesomegamergame** [comment]
Yeah but I didnt wanted to remake another pull request so I just added all the code manually to master and pushed the update in the web data folder @ArsiaC01

**Comment by Awesomegamergame** [comment]
Locking pull request now. Bye

**Comment by Awesomegamergame** [comment]
Well the lock is useless then if collaborators can still talk

**Pull request merged**
