### PR TITLE
1.2.0-Update

### LINKED ISSUE #5: Background RAM Usage
**I'm submitting a**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Other

(You only need to fill out either the Bug Report or Feature Request section)

## Bug Report 😨
* **What is the current behavior?**
High resolution pictures in wallpaper mode cause the memory to increase by alot. Also too many pictures or too many high resolution pictures also cause an increase in memory in slideshow mode even when the program is minimized in tray.

* **Please tell us about your environment:**
  
  - Version: `V1.1.0`
  - Operating System: Windows 10
  - Is this a school computer: Tested on a school computer and a non-school computer
  - List any other information you may think may be relevant here:

* **If the current behavior is a bug, please provide the steps to reproduce and submit a screenshot along with the error message.**
Load a high resolution picture like a 4k or higher and see the huge increase in ram usage

* **What is the expected behavior?**
use not so much ram and to use little amount of ram when minimized

* **Pictures**
Capture2
Capture

### PR DESCRIPTION
**Pull request by Awesomegamergame**
I'm to good to use the template

### CODE REVIEW

**Comment by Awesomegamergame** [comment]
commit 0ed62be took all the effort out of me so im going to take a break before continuing

**Comment by Awesomegamergame** [comment]
have fun with the code. Tomorrow i need to come up with a json format for all the variables to keep track of for the startup process. Also need to create a settings menu for the startup options and other stuff.

(Edit) Used ini files instead of json so i dont need another dll and ini is easier to read and use than json

**Comment by Awesomegamergame** [comment]
The ram leak is fully fixed without unloading the image hopefully will test with bigger pictures and on different computers to see if the leak is gone

**Comment by Awesomegamergame** [comment]
ok most of the saving last picture stuff is there now. need to still fix some more ui bugs. also need to save last slideshow picture in the config to start from that point when the program starts. and finally make the program start on startup and continue either the slideshow or the picture mode to refresh the ui

**Comment by Awesomegamergame** [comment]
Here's a todo of what is left that needs done.

- [x] Add as a startup process
- [x] Fix some startup bugs
- [x] Fix the ui so the correct pictures show
- [x] Read the config
- [x] Use config settings on startup
- [x] Add setting to enable and disable startup
- [x] Before release check the stupid memory usage and make sure it doesnt get out of hand
- [x] Look over the code for stupid mistakes
- [x] Test and find bugs
- [x] Fix bugs found
- [x] Add build .zip and version to webdata
- [x] Wait for github actions to build
- [x] Get reviewed

**Comment by Awesomegamergame** [comment]
The only bug that has been found is the warning message bug which should be easy to fix. If you find any other bugs @ArsiaC01 please tell me in this pull request so i can fix it

**Comment by Awesomegamergame** [comment]
Warning bug fixed with some other bug fixes see 720df03 for more info

**Comment by Awesomegamergame** [comment]
Almost forgot to re-enable the app updater

**Comment by ArsiaC01** [comment]
Not sure if you've noticed, program won't start due to a System.IO.FileNotFoundException: in ButtonClick.cs
image

**Comment by Awesomegamergame** [comment]
no i have not noticed it. im going to find out why that is happening

**Comment by Awesomegamergame** [comment]
@ArsiaC01 Ok i fixed that problem. I forgot to put the getting resolutions into the if statements. Good thing you caught that because i was about to merge the upload the entire update

**Pull request merged**
