### PR TITLE
1.3.0 Update

### LINKED ISSUE #6: Black Wallpaper on personal wifi
**I'm submitting a**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Other

(You only need to fill out either the Bug Report or Feature Request section)

## Bug Report 😨
* **What is the current behavior?**
When you aren't connected to a school network (wifi) the background will always be black.

* **Please tell us about your environment:**
  
  - Version: `V1.2.3`
  - Operating System: Windows 10
  - Is this a school computer: Yes
  - List any other information you may think may be relevant here:
This problem doesn't happen on home computers (Personal Computer) on the same wifi.

* **If the current behavior is a bug, please provide the steps to reproduce and submit a screenshot along with the error message.**
connect to any home wifi or any wifi that is not the school wifi and try to set the wallpaper or restart the computer and the black screen will appear.

Capture

* **What is the expected behavior?**
the wallpaper to actually show

### LINKED ISSUE #10: File In Use
**I'm submitting a**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Other

(You only need to fill out either the Bug Report or Feature Request section)

## Bug Report 😨
* **What is the current behavior?**
When the image is loaded into the program it still holds the file so it cant be modified or deleted until the program is closed.

* **Please tell us about your environment:**
  
  - Version: `V1.2.3`
  - **Operating System: Windows 10** 
  - **Is this a school computer: Yes, Happens on non-School Computers as well** 
  - **List any other information you may think may be relevant here:** 

Capture

* **If the current behavior is a bug, please provide the steps to reproduce and submit a screenshot along with the error message.**
Select the image and try to delete the picture after it still does it even when switching modes.

* **What is the expected behavior?**

Being able to delete the image even while its selected

### PR DESCRIPTION
**Pull request by Awesomegamergame**
* **Please check if the PR fulfills these requirements**
  - [x] The commit message follows our guidelines

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This is the 1.3.0 Feature Update. It will fix #6 Hopefully once and for all. Also fixes the #10

* **What is the current behavior?** (You can also link to an open issue here)
See Issue #6, #10

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
None

* **Other relevant information**:

None

**Todo List:**
- [x] Change the version to 1.3.0
- [x] Change the docs and readme to 1.3.0
- [x] Figure out how to make a window behind the desktop icons.
- [x] Add some windows external code.
- [x] Add it into the program (Going to fix some bugs before adding it).
- [x] Convert winforms image to wpf (Better Performance).
- [x] Test the wpf window on all aspect ratios.
- [x] Determine when the wallpaper fails to set itself.
- [x] Set the alternative wallpaper to set on startup when the normal code fails to set it.
- [x] Cleanup external functions by removing functions and variables that aren't used from the windows code
- [x] Check for bugs (Any Testing help is appreciated when we get here)
- [x] Fix Bugs (If any)
- [x] Upload Build to Webdata
- [x] Merge Pull Request (Release)

### CODE REVIEW

**Comment by awesomegamergame** [comment]
I'll fill out the pull request form tomorrow

**Comment by Awesomegamergame** [comment]
why you break my pull request

**Comment by Awesomegamergame** [comment]
Ok I fixed the branch plz dont break it again

**Comment by Awesomegamergame** [comment]
ok my win forms background image does work (thanks stackoverflow) ~~but i cant change the image once its already started so im going to have to mess around with it.~~(Fixed in Commit 92043ad just need to hook it up to the reapply button) also there are some computers that have the black screen even on school wifi.

**Comment by Awesomegamergame** [comment]
ok everything works and commit 0ed1fde is the most stable version of the program so far. use that commits build to find the bugs dont use anything newer than that one unless i say so.

**Comment by Awesomegamergame** [comment]
i got to merge the pull request i didnt see any bugs but if any are found then oh well. i just wont release it yet

**Pull request merged**
